-- sys.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library sys_clock_in;
library cpu;
library jtag_uart;
library sys_nvmm_0;
library sys_intel_onchip_memory_0;
library sys_reset_in;
library sys_sysid_qsys_0;
library altera_mm_interconnect_1920;
library altera_irq_mapper_2001;
library altera_reset_controller_1922;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys is
	port (
		clk_clk     : in std_logic := '0'; --   clk.clk
		reset_reset : in std_logic := '0'  -- reset.reset
	);
end entity sys;

architecture rtl of sys is
	component sys_clock_in_cmp is
		port (
			in_clk  : in  std_logic := 'X'; -- clk
			out_clk : out std_logic         -- clk
		);
	end component sys_clock_in_cmp;

	component cpu_cmp is
		port (
			clk                          : in  std_logic                     := 'X';             -- clk
			reset_reset                  : in  std_logic                     := 'X';             -- reset
			platform_irq_rx_irq          : in  std_logic_vector(15 downto 0) := (others => 'X'); -- irq
			instruction_manager_awaddr   : out std_logic_vector(31 downto 0);                    -- awaddr
			instruction_manager_awlen    : out std_logic_vector(7 downto 0);                     -- awlen
			instruction_manager_awsize   : out std_logic_vector(2 downto 0);                     -- awsize
			instruction_manager_awburst  : out std_logic_vector(1 downto 0);                     -- awburst
			instruction_manager_awprot   : out std_logic_vector(2 downto 0);                     -- awprot
			instruction_manager_awvalid  : out std_logic;                                        -- awvalid
			instruction_manager_awready  : in  std_logic                     := 'X';             -- awready
			instruction_manager_wdata    : out std_logic_vector(31 downto 0);                    -- wdata
			instruction_manager_wstrb    : out std_logic_vector(3 downto 0);                     -- wstrb
			instruction_manager_wlast    : out std_logic;                                        -- wlast
			instruction_manager_wvalid   : out std_logic;                                        -- wvalid
			instruction_manager_wready   : in  std_logic                     := 'X';             -- wready
			instruction_manager_bresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			instruction_manager_bvalid   : in  std_logic                     := 'X';             -- bvalid
			instruction_manager_bready   : out std_logic;                                        -- bready
			instruction_manager_araddr   : out std_logic_vector(31 downto 0);                    -- araddr
			instruction_manager_arlen    : out std_logic_vector(7 downto 0);                     -- arlen
			instruction_manager_arsize   : out std_logic_vector(2 downto 0);                     -- arsize
			instruction_manager_arburst  : out std_logic_vector(1 downto 0);                     -- arburst
			instruction_manager_arprot   : out std_logic_vector(2 downto 0);                     -- arprot
			instruction_manager_arvalid  : out std_logic;                                        -- arvalid
			instruction_manager_arready  : in  std_logic                     := 'X';             -- arready
			instruction_manager_rdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			instruction_manager_rresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			instruction_manager_rlast    : in  std_logic                     := 'X';             -- rlast
			instruction_manager_rvalid   : in  std_logic                     := 'X';             -- rvalid
			instruction_manager_rready   : out std_logic;                                        -- rready
			data_manager_awaddr          : out std_logic_vector(31 downto 0);                    -- awaddr
			data_manager_awlen           : out std_logic_vector(7 downto 0);                     -- awlen
			data_manager_awsize          : out std_logic_vector(2 downto 0);                     -- awsize
			data_manager_awprot          : out std_logic_vector(2 downto 0);                     -- awprot
			data_manager_awvalid         : out std_logic;                                        -- awvalid
			data_manager_awready         : in  std_logic                     := 'X';             -- awready
			data_manager_wdata           : out std_logic_vector(31 downto 0);                    -- wdata
			data_manager_wstrb           : out std_logic_vector(3 downto 0);                     -- wstrb
			data_manager_wlast           : out std_logic;                                        -- wlast
			data_manager_wvalid          : out std_logic;                                        -- wvalid
			data_manager_wready          : in  std_logic                     := 'X';             -- wready
			data_manager_bresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			data_manager_bvalid          : in  std_logic                     := 'X';             -- bvalid
			data_manager_bready          : out std_logic;                                        -- bready
			data_manager_araddr          : out std_logic_vector(31 downto 0);                    -- araddr
			data_manager_arlen           : out std_logic_vector(7 downto 0);                     -- arlen
			data_manager_arsize          : out std_logic_vector(2 downto 0);                     -- arsize
			data_manager_arprot          : out std_logic_vector(2 downto 0);                     -- arprot
			data_manager_arvalid         : out std_logic;                                        -- arvalid
			data_manager_arready         : in  std_logic                     := 'X';             -- arready
			data_manager_rdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			data_manager_rresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			data_manager_rlast           : in  std_logic                     := 'X';             -- rlast
			data_manager_rvalid          : in  std_logic                     := 'X';             -- rvalid
			data_manager_rready          : out std_logic;                                        -- rready
			ci_custom0_clk               : out std_logic;                                        -- clk
			ci_custom0_reset             : out std_logic;                                        -- reset
			ci_custom0_data0             : out std_logic_vector(31 downto 0);                    -- data0
			ci_custom0_data1             : out std_logic_vector(31 downto 0);                    -- data1
			ci_custom0_ctrl              : out std_logic_vector(31 downto 0);                    -- ctrl
			ci_custom0_alu_result        : out std_logic_vector(31 downto 0);                    -- alu_result
			ci_custom0_enable            : out std_logic;                                        -- enable
			ci_custom0_result            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- result
			ci_custom0_done              : in  std_logic                     := 'X';             -- done
			timer_sw_agent_address       : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- address
			timer_sw_agent_byteenable    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			timer_sw_agent_read          : in  std_logic                     := 'X';             -- read
			timer_sw_agent_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			timer_sw_agent_write         : in  std_logic                     := 'X';             -- write
			timer_sw_agent_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			timer_sw_agent_waitrequest   : out std_logic;                                        -- waitrequest
			timer_sw_agent_readdatavalid : out std_logic;                                        -- readdatavalid
			dm_agent_address             : in  std_logic_vector(15 downto 0) := (others => 'X'); -- address
			dm_agent_read                : in  std_logic                     := 'X';             -- read
			dm_agent_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			dm_agent_write               : in  std_logic                     := 'X';             -- write
			dm_agent_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			dm_agent_waitrequest         : out std_logic;                                        -- waitrequest
			dm_agent_readdatavalid       : out std_logic                                         -- readdatavalid
		);
	end component cpu_cmp;

	component jtag_uart_cmp is
		port (
			clk            : in  std_logic                     := 'X';             -- clk
			rst_n          : in  std_logic                     := 'X';             -- reset_n
			av_chipselect  : in  std_logic                     := 'X';             -- chipselect
			av_address     : in  std_logic                     := 'X';             -- address
			av_read_n      : in  std_logic                     := 'X';             -- read_n
			av_readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			av_write_n     : in  std_logic                     := 'X';             -- write_n
			av_writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_waitrequest : out std_logic;                                        -- waitrequest
			av_irq         : out std_logic                                         -- irq
		);
	end component jtag_uart_cmp;

	component sys_nvmm_0_cmp is
		generic (
			N : integer := 25;
			K : integer := 5
		);
		port (
			NVMM_alu_result : in  std_logic_vector(31 downto 0) := (others => 'X'); -- alu_result
			NVMM_clk        : in  std_logic                     := 'X';             -- clk
			NVMM_ctrl       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- ctrl
			NVMM_data0      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data0
			NVMM_data1      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data1
			NVMM_done       : out std_logic;                                        -- done
			NVMM_enable     : in  std_logic                     := 'X';             -- enable
			NVMM_reset      : in  std_logic                     := 'X';             -- reset
			NVMM_result     : out std_logic_vector(31 downto 0)                     -- result
		);
	end component sys_nvmm_0_cmp;

	component sys_intel_onchip_memory_0_cmp is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(18 downto 0) := (others => 'X'); -- address
			read       : in  std_logic                     := 'X';             -- read
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			write      : in  std_logic                     := 'X';             -- write
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X'              -- reset_req
		);
	end component sys_intel_onchip_memory_0_cmp;

	component sys_reset_in_cmp is
		port (
			in_reset  : in  std_logic := 'X'; -- reset
			out_reset : out std_logic         -- reset
		);
	end component sys_reset_in_cmp;

	component sys_sysid_qsys_0_cmp is
		port (
			clock    : in  std_logic                     := 'X'; -- clk
			reset_n  : in  std_logic                     := 'X'; -- reset_n
			readdata : out std_logic_vector(31 downto 0);        -- readdata
			address  : in  std_logic                     := 'X'  -- address
		);
	end component sys_sysid_qsys_0_cmp;

	component sys_altera_mm_interconnect_1920_wvxmrgi_cmp is
		port (
			cpu_data_manager_awaddr                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- awaddr
			cpu_data_manager_awlen                  : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			cpu_data_manager_awsize                 : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			cpu_data_manager_awprot                 : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			cpu_data_manager_awvalid                : in  std_logic                     := 'X';             -- awvalid
			cpu_data_manager_awready                : out std_logic;                                        -- awready
			cpu_data_manager_wdata                  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			cpu_data_manager_wstrb                  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			cpu_data_manager_wlast                  : in  std_logic                     := 'X';             -- wlast
			cpu_data_manager_wvalid                 : in  std_logic                     := 'X';             -- wvalid
			cpu_data_manager_wready                 : out std_logic;                                        -- wready
			cpu_data_manager_bresp                  : out std_logic_vector(1 downto 0);                     -- bresp
			cpu_data_manager_bvalid                 : out std_logic;                                        -- bvalid
			cpu_data_manager_bready                 : in  std_logic                     := 'X';             -- bready
			cpu_data_manager_araddr                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- araddr
			cpu_data_manager_arlen                  : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			cpu_data_manager_arsize                 : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			cpu_data_manager_arprot                 : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			cpu_data_manager_arvalid                : in  std_logic                     := 'X';             -- arvalid
			cpu_data_manager_arready                : out std_logic;                                        -- arready
			cpu_data_manager_rdata                  : out std_logic_vector(31 downto 0);                    -- rdata
			cpu_data_manager_rresp                  : out std_logic_vector(1 downto 0);                     -- rresp
			cpu_data_manager_rlast                  : out std_logic;                                        -- rlast
			cpu_data_manager_rvalid                 : out std_logic;                                        -- rvalid
			cpu_data_manager_rready                 : in  std_logic                     := 'X';             -- rready
			cpu_instruction_manager_awaddr          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- awaddr
			cpu_instruction_manager_awlen           : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			cpu_instruction_manager_awsize          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			cpu_instruction_manager_awburst         : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- awburst
			cpu_instruction_manager_awprot          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			cpu_instruction_manager_awvalid         : in  std_logic                     := 'X';             -- awvalid
			cpu_instruction_manager_awready         : out std_logic;                                        -- awready
			cpu_instruction_manager_wdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			cpu_instruction_manager_wstrb           : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			cpu_instruction_manager_wlast           : in  std_logic                     := 'X';             -- wlast
			cpu_instruction_manager_wvalid          : in  std_logic                     := 'X';             -- wvalid
			cpu_instruction_manager_wready          : out std_logic;                                        -- wready
			cpu_instruction_manager_bresp           : out std_logic_vector(1 downto 0);                     -- bresp
			cpu_instruction_manager_bvalid          : out std_logic;                                        -- bvalid
			cpu_instruction_manager_bready          : in  std_logic                     := 'X';             -- bready
			cpu_instruction_manager_araddr          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- araddr
			cpu_instruction_manager_arlen           : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			cpu_instruction_manager_arsize          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			cpu_instruction_manager_arburst         : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- arburst
			cpu_instruction_manager_arprot          : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			cpu_instruction_manager_arvalid         : in  std_logic                     := 'X';             -- arvalid
			cpu_instruction_manager_arready         : out std_logic;                                        -- arready
			cpu_instruction_manager_rdata           : out std_logic_vector(31 downto 0);                    -- rdata
			cpu_instruction_manager_rresp           : out std_logic_vector(1 downto 0);                     -- rresp
			cpu_instruction_manager_rlast           : out std_logic;                                        -- rlast
			cpu_instruction_manager_rvalid          : out std_logic;                                        -- rvalid
			cpu_instruction_manager_rready          : in  std_logic                     := 'X';             -- rready
			jtag_uart_avalon_jtag_slave_address     : out std_logic_vector(0 downto 0);                     -- address
			jtag_uart_avalon_jtag_slave_write       : out std_logic;                                        -- write
			jtag_uart_avalon_jtag_slave_read        : out std_logic;                                        -- read
			jtag_uart_avalon_jtag_slave_readdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			jtag_uart_avalon_jtag_slave_writedata   : out std_logic_vector(31 downto 0);                    -- writedata
			jtag_uart_avalon_jtag_slave_waitrequest : in  std_logic                     := 'X';             -- waitrequest
			jtag_uart_avalon_jtag_slave_chipselect  : out std_logic;                                        -- chipselect
			sysid_qsys_0_control_slave_address      : out std_logic_vector(0 downto 0);                     -- address
			sysid_qsys_0_control_slave_readdata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			cpu_dm_agent_address                    : out std_logic_vector(15 downto 0);                    -- address
			cpu_dm_agent_write                      : out std_logic;                                        -- write
			cpu_dm_agent_read                       : out std_logic;                                        -- read
			cpu_dm_agent_readdata                   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			cpu_dm_agent_writedata                  : out std_logic_vector(31 downto 0);                    -- writedata
			cpu_dm_agent_readdatavalid              : in  std_logic                     := 'X';             -- readdatavalid
			cpu_dm_agent_waitrequest                : in  std_logic                     := 'X';             -- waitrequest
			ram_s1_address                          : out std_logic_vector(18 downto 0);                    -- address
			ram_s1_write                            : out std_logic;                                        -- write
			ram_s1_read                             : out std_logic;                                        -- read
			ram_s1_readdata                         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			ram_s1_writedata                        : out std_logic_vector(31 downto 0);                    -- writedata
			ram_s1_byteenable                       : out std_logic_vector(3 downto 0);                     -- byteenable
			cpu_timer_sw_agent_address              : out std_logic_vector(5 downto 0);                     -- address
			cpu_timer_sw_agent_write                : out std_logic;                                        -- write
			cpu_timer_sw_agent_read                 : out std_logic;                                        -- read
			cpu_timer_sw_agent_readdata             : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			cpu_timer_sw_agent_writedata            : out std_logic_vector(31 downto 0);                    -- writedata
			cpu_timer_sw_agent_byteenable           : out std_logic_vector(3 downto 0);                     -- byteenable
			cpu_timer_sw_agent_readdatavalid        : in  std_logic                     := 'X';             -- readdatavalid
			cpu_timer_sw_agent_waitrequest          : in  std_logic                     := 'X';             -- waitrequest
			cpu_reset_reset_bridge_in_reset_reset   : in  std_logic                     := 'X';             -- reset
			clock_in_out_clk_clk                    : in  std_logic                     := 'X'              -- clk
		);
	end component sys_altera_mm_interconnect_1920_wvxmrgi_cmp;

	component sys_altera_irq_mapper_2001_ghcid5i_cmp is
		port (
			clk           : in  std_logic                     := 'X'; -- clk
			reset         : in  std_logic                     := 'X'; -- reset
			receiver0_irq : in  std_logic                     := 'X'; -- irq
			sender_irq    : out std_logic_vector(15 downto 0)         -- irq
		);
	end component sys_altera_irq_mapper_2001_ghcid5i_cmp;

	component altera_reset_controller_cmp is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller_cmp;

	signal clock_in_out_clk_clk                                          : std_logic;                     -- clock_in:out_clk -> [cpu:clk, irq_mapper:clk, jtag_uart:clk, mm_interconnect_0:clock_in_out_clk_clk, ram:clk, rst_controller:clk, sysid_qsys_0:clock]
	signal cpu_ci_custom0_result                                         : std_logic_vector(31 downto 0); -- nvmm:NVMM_result -> cpu:ci_custom0_result
	signal cpu_ci_custom0_clk                                            : std_logic;                     -- cpu:ci_custom0_clk -> nvmm:NVMM_clk
	signal cpu_ci_custom0_ctrl                                           : std_logic_vector(31 downto 0); -- cpu:ci_custom0_ctrl -> nvmm:NVMM_ctrl
	signal cpu_ci_custom0_enable                                         : std_logic;                     -- cpu:ci_custom0_enable -> nvmm:NVMM_enable
	signal cpu_ci_custom0_data1                                          : std_logic_vector(31 downto 0); -- cpu:ci_custom0_data1 -> nvmm:NVMM_data1
	signal cpu_ci_custom0_reset                                          : std_logic;                     -- cpu:ci_custom0_reset -> nvmm:NVMM_reset
	signal cpu_ci_custom0_data0                                          : std_logic_vector(31 downto 0); -- cpu:ci_custom0_data0 -> nvmm:NVMM_data0
	signal cpu_ci_custom0_alu_result                                     : std_logic_vector(31 downto 0); -- cpu:ci_custom0_alu_result -> nvmm:NVMM_alu_result
	signal cpu_ci_custom0_done                                           : std_logic;                     -- nvmm:NVMM_done -> cpu:ci_custom0_done
	signal cpu_data_manager_arlen                                        : std_logic_vector(7 downto 0);  -- cpu:data_manager_arlen -> mm_interconnect_0:cpu_data_manager_arlen
	signal cpu_data_manager_wstrb                                        : std_logic_vector(3 downto 0);  -- cpu:data_manager_wstrb -> mm_interconnect_0:cpu_data_manager_wstrb
	signal cpu_data_manager_wready                                       : std_logic;                     -- mm_interconnect_0:cpu_data_manager_wready -> cpu:data_manager_wready
	signal cpu_data_manager_rready                                       : std_logic;                     -- cpu:data_manager_rready -> mm_interconnect_0:cpu_data_manager_rready
	signal cpu_data_manager_awlen                                        : std_logic_vector(7 downto 0);  -- cpu:data_manager_awlen -> mm_interconnect_0:cpu_data_manager_awlen
	signal cpu_data_manager_wvalid                                       : std_logic;                     -- cpu:data_manager_wvalid -> mm_interconnect_0:cpu_data_manager_wvalid
	signal cpu_data_manager_araddr                                       : std_logic_vector(31 downto 0); -- cpu:data_manager_araddr -> mm_interconnect_0:cpu_data_manager_araddr
	signal cpu_data_manager_arprot                                       : std_logic_vector(2 downto 0);  -- cpu:data_manager_arprot -> mm_interconnect_0:cpu_data_manager_arprot
	signal cpu_data_manager_awprot                                       : std_logic_vector(2 downto 0);  -- cpu:data_manager_awprot -> mm_interconnect_0:cpu_data_manager_awprot
	signal cpu_data_manager_wdata                                        : std_logic_vector(31 downto 0); -- cpu:data_manager_wdata -> mm_interconnect_0:cpu_data_manager_wdata
	signal cpu_data_manager_arvalid                                      : std_logic;                     -- cpu:data_manager_arvalid -> mm_interconnect_0:cpu_data_manager_arvalid
	signal cpu_data_manager_awaddr                                       : std_logic_vector(31 downto 0); -- cpu:data_manager_awaddr -> mm_interconnect_0:cpu_data_manager_awaddr
	signal cpu_data_manager_bresp                                        : std_logic_vector(1 downto 0);  -- mm_interconnect_0:cpu_data_manager_bresp -> cpu:data_manager_bresp
	signal cpu_data_manager_arready                                      : std_logic;                     -- mm_interconnect_0:cpu_data_manager_arready -> cpu:data_manager_arready
	signal cpu_data_manager_rdata                                        : std_logic_vector(31 downto 0); -- mm_interconnect_0:cpu_data_manager_rdata -> cpu:data_manager_rdata
	signal cpu_data_manager_awready                                      : std_logic;                     -- mm_interconnect_0:cpu_data_manager_awready -> cpu:data_manager_awready
	signal cpu_data_manager_arsize                                       : std_logic_vector(2 downto 0);  -- cpu:data_manager_arsize -> mm_interconnect_0:cpu_data_manager_arsize
	signal cpu_data_manager_bready                                       : std_logic;                     -- cpu:data_manager_bready -> mm_interconnect_0:cpu_data_manager_bready
	signal cpu_data_manager_rlast                                        : std_logic;                     -- mm_interconnect_0:cpu_data_manager_rlast -> cpu:data_manager_rlast
	signal cpu_data_manager_wlast                                        : std_logic;                     -- cpu:data_manager_wlast -> mm_interconnect_0:cpu_data_manager_wlast
	signal cpu_data_manager_rresp                                        : std_logic_vector(1 downto 0);  -- mm_interconnect_0:cpu_data_manager_rresp -> cpu:data_manager_rresp
	signal cpu_data_manager_bvalid                                       : std_logic;                     -- mm_interconnect_0:cpu_data_manager_bvalid -> cpu:data_manager_bvalid
	signal cpu_data_manager_awsize                                       : std_logic_vector(2 downto 0);  -- cpu:data_manager_awsize -> mm_interconnect_0:cpu_data_manager_awsize
	signal cpu_data_manager_awvalid                                      : std_logic;                     -- cpu:data_manager_awvalid -> mm_interconnect_0:cpu_data_manager_awvalid
	signal cpu_data_manager_rvalid                                       : std_logic;                     -- mm_interconnect_0:cpu_data_manager_rvalid -> cpu:data_manager_rvalid
	signal cpu_instruction_manager_awburst                               : std_logic_vector(1 downto 0);  -- cpu:instruction_manager_awburst -> mm_interconnect_0:cpu_instruction_manager_awburst
	signal cpu_instruction_manager_arlen                                 : std_logic_vector(7 downto 0);  -- cpu:instruction_manager_arlen -> mm_interconnect_0:cpu_instruction_manager_arlen
	signal cpu_instruction_manager_wstrb                                 : std_logic_vector(3 downto 0);  -- cpu:instruction_manager_wstrb -> mm_interconnect_0:cpu_instruction_manager_wstrb
	signal cpu_instruction_manager_wready                                : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_wready -> cpu:instruction_manager_wready
	signal cpu_instruction_manager_rready                                : std_logic;                     -- cpu:instruction_manager_rready -> mm_interconnect_0:cpu_instruction_manager_rready
	signal cpu_instruction_manager_awlen                                 : std_logic_vector(7 downto 0);  -- cpu:instruction_manager_awlen -> mm_interconnect_0:cpu_instruction_manager_awlen
	signal cpu_instruction_manager_wvalid                                : std_logic;                     -- cpu:instruction_manager_wvalid -> mm_interconnect_0:cpu_instruction_manager_wvalid
	signal cpu_instruction_manager_araddr                                : std_logic_vector(31 downto 0); -- cpu:instruction_manager_araddr -> mm_interconnect_0:cpu_instruction_manager_araddr
	signal cpu_instruction_manager_arprot                                : std_logic_vector(2 downto 0);  -- cpu:instruction_manager_arprot -> mm_interconnect_0:cpu_instruction_manager_arprot
	signal cpu_instruction_manager_awprot                                : std_logic_vector(2 downto 0);  -- cpu:instruction_manager_awprot -> mm_interconnect_0:cpu_instruction_manager_awprot
	signal cpu_instruction_manager_wdata                                 : std_logic_vector(31 downto 0); -- cpu:instruction_manager_wdata -> mm_interconnect_0:cpu_instruction_manager_wdata
	signal cpu_instruction_manager_arvalid                               : std_logic;                     -- cpu:instruction_manager_arvalid -> mm_interconnect_0:cpu_instruction_manager_arvalid
	signal cpu_instruction_manager_awaddr                                : std_logic_vector(31 downto 0); -- cpu:instruction_manager_awaddr -> mm_interconnect_0:cpu_instruction_manager_awaddr
	signal cpu_instruction_manager_bresp                                 : std_logic_vector(1 downto 0);  -- mm_interconnect_0:cpu_instruction_manager_bresp -> cpu:instruction_manager_bresp
	signal cpu_instruction_manager_arready                               : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_arready -> cpu:instruction_manager_arready
	signal cpu_instruction_manager_rdata                                 : std_logic_vector(31 downto 0); -- mm_interconnect_0:cpu_instruction_manager_rdata -> cpu:instruction_manager_rdata
	signal cpu_instruction_manager_awready                               : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_awready -> cpu:instruction_manager_awready
	signal cpu_instruction_manager_arburst                               : std_logic_vector(1 downto 0);  -- cpu:instruction_manager_arburst -> mm_interconnect_0:cpu_instruction_manager_arburst
	signal cpu_instruction_manager_arsize                                : std_logic_vector(2 downto 0);  -- cpu:instruction_manager_arsize -> mm_interconnect_0:cpu_instruction_manager_arsize
	signal cpu_instruction_manager_bready                                : std_logic;                     -- cpu:instruction_manager_bready -> mm_interconnect_0:cpu_instruction_manager_bready
	signal cpu_instruction_manager_rlast                                 : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_rlast -> cpu:instruction_manager_rlast
	signal cpu_instruction_manager_wlast                                 : std_logic;                     -- cpu:instruction_manager_wlast -> mm_interconnect_0:cpu_instruction_manager_wlast
	signal cpu_instruction_manager_rresp                                 : std_logic_vector(1 downto 0);  -- mm_interconnect_0:cpu_instruction_manager_rresp -> cpu:instruction_manager_rresp
	signal cpu_instruction_manager_bvalid                                : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_bvalid -> cpu:instruction_manager_bvalid
	signal cpu_instruction_manager_awsize                                : std_logic_vector(2 downto 0);  -- cpu:instruction_manager_awsize -> mm_interconnect_0:cpu_instruction_manager_awsize
	signal cpu_instruction_manager_awvalid                               : std_logic;                     -- cpu:instruction_manager_awvalid -> mm_interconnect_0:cpu_instruction_manager_awvalid
	signal cpu_instruction_manager_rvalid                                : std_logic;                     -- mm_interconnect_0:cpu_instruction_manager_rvalid -> cpu:instruction_manager_rvalid
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect      : std_logic;                     -- mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata        : std_logic_vector(31 downto 0); -- jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest     : std_logic;                     -- jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_address         : std_logic_vector(0 downto 0);  -- mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read            : std_logic;                     -- mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write           : std_logic;                     -- mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata       : std_logic_vector(31 downto 0); -- mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	signal mm_interconnect_0_sysid_qsys_0_control_slave_readdata         : std_logic_vector(31 downto 0); -- sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	signal mm_interconnect_0_sysid_qsys_0_control_slave_address          : std_logic_vector(0 downto 0);  -- mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	signal mm_interconnect_0_cpu_dm_agent_readdata                       : std_logic_vector(31 downto 0); -- cpu:dm_agent_readdata -> mm_interconnect_0:cpu_dm_agent_readdata
	signal mm_interconnect_0_cpu_dm_agent_waitrequest                    : std_logic;                     -- cpu:dm_agent_waitrequest -> mm_interconnect_0:cpu_dm_agent_waitrequest
	signal mm_interconnect_0_cpu_dm_agent_address                        : std_logic_vector(15 downto 0); -- mm_interconnect_0:cpu_dm_agent_address -> cpu:dm_agent_address
	signal mm_interconnect_0_cpu_dm_agent_read                           : std_logic;                     -- mm_interconnect_0:cpu_dm_agent_read -> cpu:dm_agent_read
	signal mm_interconnect_0_cpu_dm_agent_readdatavalid                  : std_logic;                     -- cpu:dm_agent_readdatavalid -> mm_interconnect_0:cpu_dm_agent_readdatavalid
	signal mm_interconnect_0_cpu_dm_agent_write                          : std_logic;                     -- mm_interconnect_0:cpu_dm_agent_write -> cpu:dm_agent_write
	signal mm_interconnect_0_cpu_dm_agent_writedata                      : std_logic_vector(31 downto 0); -- mm_interconnect_0:cpu_dm_agent_writedata -> cpu:dm_agent_writedata
	signal mm_interconnect_0_ram_s1_readdata                             : std_logic_vector(31 downto 0); -- ram:readdata -> mm_interconnect_0:ram_s1_readdata
	signal mm_interconnect_0_ram_s1_address                              : std_logic_vector(18 downto 0); -- mm_interconnect_0:ram_s1_address -> ram:address
	signal mm_interconnect_0_ram_s1_read                                 : std_logic;                     -- mm_interconnect_0:ram_s1_read -> ram:read
	signal mm_interconnect_0_ram_s1_byteenable                           : std_logic_vector(3 downto 0);  -- mm_interconnect_0:ram_s1_byteenable -> ram:byteenable
	signal mm_interconnect_0_ram_s1_write                                : std_logic;                     -- mm_interconnect_0:ram_s1_write -> ram:write
	signal mm_interconnect_0_ram_s1_writedata                            : std_logic_vector(31 downto 0); -- mm_interconnect_0:ram_s1_writedata -> ram:writedata
	signal mm_interconnect_0_cpu_timer_sw_agent_readdata                 : std_logic_vector(31 downto 0); -- cpu:timer_sw_agent_readdata -> mm_interconnect_0:cpu_timer_sw_agent_readdata
	signal mm_interconnect_0_cpu_timer_sw_agent_waitrequest              : std_logic;                     -- cpu:timer_sw_agent_waitrequest -> mm_interconnect_0:cpu_timer_sw_agent_waitrequest
	signal mm_interconnect_0_cpu_timer_sw_agent_address                  : std_logic_vector(5 downto 0);  -- mm_interconnect_0:cpu_timer_sw_agent_address -> cpu:timer_sw_agent_address
	signal mm_interconnect_0_cpu_timer_sw_agent_read                     : std_logic;                     -- mm_interconnect_0:cpu_timer_sw_agent_read -> cpu:timer_sw_agent_read
	signal mm_interconnect_0_cpu_timer_sw_agent_byteenable               : std_logic_vector(3 downto 0);  -- mm_interconnect_0:cpu_timer_sw_agent_byteenable -> cpu:timer_sw_agent_byteenable
	signal mm_interconnect_0_cpu_timer_sw_agent_readdatavalid            : std_logic;                     -- cpu:timer_sw_agent_readdatavalid -> mm_interconnect_0:cpu_timer_sw_agent_readdatavalid
	signal mm_interconnect_0_cpu_timer_sw_agent_write                    : std_logic;                     -- mm_interconnect_0:cpu_timer_sw_agent_write -> cpu:timer_sw_agent_write
	signal mm_interconnect_0_cpu_timer_sw_agent_writedata                : std_logic_vector(31 downto 0); -- mm_interconnect_0:cpu_timer_sw_agent_writedata -> cpu:timer_sw_agent_writedata
	signal irq_mapper_receiver0_irq                                      : std_logic;                     -- jtag_uart:av_irq -> irq_mapper:receiver0_irq
	signal cpu_platform_irq_rx_irq                                       : std_logic_vector(15 downto 0); -- irq_mapper:sender_irq -> cpu:platform_irq_rx_irq
	signal rst_controller_reset_out_reset                                : std_logic;                     -- rst_controller:reset_out -> [cpu:reset_reset, irq_mapper:reset, mm_interconnect_0:cpu_reset_reset_bridge_in_reset_reset, ram:reset, rst_controller_reset_out_reset:in, rst_translator:in_reset]
	signal rst_controller_reset_out_reset_req                            : std_logic;                     -- rst_controller:reset_req -> [ram:reset_req, rst_translator:reset_req_in]
	signal reset_in_out_reset_reset                                      : std_logic;                     -- reset_in:out_reset -> rst_controller:reset_in0
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv  : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:inv -> jtag_uart:av_read_n
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:inv -> jtag_uart:av_write_n
	signal rst_controller_reset_out_reset_ports_inv                      : std_logic;                     -- rst_controller_reset_out_reset:inv -> [jtag_uart:rst_n, sysid_qsys_0:reset_n]

	for clock_in : sys_clock_in_cmp
		use entity sys_clock_in.sys_clock_in;
	for cpu : cpu_cmp
		use entity cpu.cpu;
	for jtag_uart : jtag_uart_cmp
		use entity jtag_uart.jtag_uart;
	for nvmm : sys_nvmm_0_cmp
		use entity sys_nvmm_0.sys_nvmm_0;
	for ram : sys_intel_onchip_memory_0_cmp
		use entity sys_intel_onchip_memory_0.sys_intel_onchip_memory_0;
	for reset_in : sys_reset_in_cmp
		use entity sys_reset_in.sys_reset_in;
	for sysid_qsys_0 : sys_sysid_qsys_0_cmp
		use entity sys_sysid_qsys_0.sys_sysid_qsys_0;
	for mm_interconnect_0 : sys_altera_mm_interconnect_1920_wvxmrgi_cmp
		use entity altera_mm_interconnect_1920.sys_altera_mm_interconnect_1920_wvxmrgi;
	for irq_mapper : sys_altera_irq_mapper_2001_ghcid5i_cmp
		use entity altera_irq_mapper_2001.sys_altera_irq_mapper_2001_ghcid5i;
	for rst_controller : altera_reset_controller_cmp
		use entity altera_reset_controller_1922.altera_reset_controller;
begin

	clock_in : component sys_clock_in_cmp
		port map (
			in_clk  => clk_clk,              --  in_clk.clk
			out_clk => clock_in_out_clk_clk  -- out_clk.clk
		);

	cpu : component cpu_cmp
		port map (
			clk                          => clock_in_out_clk_clk,                               --                 clk.clk
			reset_reset                  => rst_controller_reset_out_reset,                     --               reset.reset
			platform_irq_rx_irq          => cpu_platform_irq_rx_irq,                            --     platform_irq_rx.irq
			instruction_manager_awaddr   => cpu_instruction_manager_awaddr,                     -- instruction_manager.awaddr
			instruction_manager_awlen    => cpu_instruction_manager_awlen,                      --                    .awlen
			instruction_manager_awsize   => cpu_instruction_manager_awsize,                     --                    .awsize
			instruction_manager_awburst  => cpu_instruction_manager_awburst,                    --                    .awburst
			instruction_manager_awprot   => cpu_instruction_manager_awprot,                     --                    .awprot
			instruction_manager_awvalid  => cpu_instruction_manager_awvalid,                    --                    .awvalid
			instruction_manager_awready  => cpu_instruction_manager_awready,                    --                    .awready
			instruction_manager_wdata    => cpu_instruction_manager_wdata,                      --                    .wdata
			instruction_manager_wstrb    => cpu_instruction_manager_wstrb,                      --                    .wstrb
			instruction_manager_wlast    => cpu_instruction_manager_wlast,                      --                    .wlast
			instruction_manager_wvalid   => cpu_instruction_manager_wvalid,                     --                    .wvalid
			instruction_manager_wready   => cpu_instruction_manager_wready,                     --                    .wready
			instruction_manager_bresp    => cpu_instruction_manager_bresp,                      --                    .bresp
			instruction_manager_bvalid   => cpu_instruction_manager_bvalid,                     --                    .bvalid
			instruction_manager_bready   => cpu_instruction_manager_bready,                     --                    .bready
			instruction_manager_araddr   => cpu_instruction_manager_araddr,                     --                    .araddr
			instruction_manager_arlen    => cpu_instruction_manager_arlen,                      --                    .arlen
			instruction_manager_arsize   => cpu_instruction_manager_arsize,                     --                    .arsize
			instruction_manager_arburst  => cpu_instruction_manager_arburst,                    --                    .arburst
			instruction_manager_arprot   => cpu_instruction_manager_arprot,                     --                    .arprot
			instruction_manager_arvalid  => cpu_instruction_manager_arvalid,                    --                    .arvalid
			instruction_manager_arready  => cpu_instruction_manager_arready,                    --                    .arready
			instruction_manager_rdata    => cpu_instruction_manager_rdata,                      --                    .rdata
			instruction_manager_rresp    => cpu_instruction_manager_rresp,                      --                    .rresp
			instruction_manager_rlast    => cpu_instruction_manager_rlast,                      --                    .rlast
			instruction_manager_rvalid   => cpu_instruction_manager_rvalid,                     --                    .rvalid
			instruction_manager_rready   => cpu_instruction_manager_rready,                     --                    .rready
			data_manager_awaddr          => cpu_data_manager_awaddr,                            --        data_manager.awaddr
			data_manager_awlen           => cpu_data_manager_awlen,                             --                    .awlen
			data_manager_awsize          => cpu_data_manager_awsize,                            --                    .awsize
			data_manager_awprot          => cpu_data_manager_awprot,                            --                    .awprot
			data_manager_awvalid         => cpu_data_manager_awvalid,                           --                    .awvalid
			data_manager_awready         => cpu_data_manager_awready,                           --                    .awready
			data_manager_wdata           => cpu_data_manager_wdata,                             --                    .wdata
			data_manager_wstrb           => cpu_data_manager_wstrb,                             --                    .wstrb
			data_manager_wlast           => cpu_data_manager_wlast,                             --                    .wlast
			data_manager_wvalid          => cpu_data_manager_wvalid,                            --                    .wvalid
			data_manager_wready          => cpu_data_manager_wready,                            --                    .wready
			data_manager_bresp           => cpu_data_manager_bresp,                             --                    .bresp
			data_manager_bvalid          => cpu_data_manager_bvalid,                            --                    .bvalid
			data_manager_bready          => cpu_data_manager_bready,                            --                    .bready
			data_manager_araddr          => cpu_data_manager_araddr,                            --                    .araddr
			data_manager_arlen           => cpu_data_manager_arlen,                             --                    .arlen
			data_manager_arsize          => cpu_data_manager_arsize,                            --                    .arsize
			data_manager_arprot          => cpu_data_manager_arprot,                            --                    .arprot
			data_manager_arvalid         => cpu_data_manager_arvalid,                           --                    .arvalid
			data_manager_arready         => cpu_data_manager_arready,                           --                    .arready
			data_manager_rdata           => cpu_data_manager_rdata,                             --                    .rdata
			data_manager_rresp           => cpu_data_manager_rresp,                             --                    .rresp
			data_manager_rlast           => cpu_data_manager_rlast,                             --                    .rlast
			data_manager_rvalid          => cpu_data_manager_rvalid,                            --                    .rvalid
			data_manager_rready          => cpu_data_manager_rready,                            --                    .rready
			ci_custom0_clk               => cpu_ci_custom0_clk,                                 --          ci_custom0.clk
			ci_custom0_reset             => cpu_ci_custom0_reset,                               --                    .reset
			ci_custom0_data0             => cpu_ci_custom0_data0,                               --                    .data0
			ci_custom0_data1             => cpu_ci_custom0_data1,                               --                    .data1
			ci_custom0_ctrl              => cpu_ci_custom0_ctrl,                                --                    .ctrl
			ci_custom0_alu_result        => cpu_ci_custom0_alu_result,                          --                    .alu_result
			ci_custom0_enable            => cpu_ci_custom0_enable,                              --                    .enable
			ci_custom0_result            => cpu_ci_custom0_result,                              --                    .result
			ci_custom0_done              => cpu_ci_custom0_done,                                --                    .done
			timer_sw_agent_address       => mm_interconnect_0_cpu_timer_sw_agent_address,       --      timer_sw_agent.address
			timer_sw_agent_byteenable    => mm_interconnect_0_cpu_timer_sw_agent_byteenable,    --                    .byteenable
			timer_sw_agent_read          => mm_interconnect_0_cpu_timer_sw_agent_read,          --                    .read
			timer_sw_agent_readdata      => mm_interconnect_0_cpu_timer_sw_agent_readdata,      --                    .readdata
			timer_sw_agent_write         => mm_interconnect_0_cpu_timer_sw_agent_write,         --                    .write
			timer_sw_agent_writedata     => mm_interconnect_0_cpu_timer_sw_agent_writedata,     --                    .writedata
			timer_sw_agent_waitrequest   => mm_interconnect_0_cpu_timer_sw_agent_waitrequest,   --                    .waitrequest
			timer_sw_agent_readdatavalid => mm_interconnect_0_cpu_timer_sw_agent_readdatavalid, --                    .readdatavalid
			dm_agent_address             => mm_interconnect_0_cpu_dm_agent_address,             --            dm_agent.address
			dm_agent_read                => mm_interconnect_0_cpu_dm_agent_read,                --                    .read
			dm_agent_readdata            => mm_interconnect_0_cpu_dm_agent_readdata,            --                    .readdata
			dm_agent_write               => mm_interconnect_0_cpu_dm_agent_write,               --                    .write
			dm_agent_writedata           => mm_interconnect_0_cpu_dm_agent_writedata,           --                    .writedata
			dm_agent_waitrequest         => mm_interconnect_0_cpu_dm_agent_waitrequest,         --                    .waitrequest
			dm_agent_readdatavalid       => mm_interconnect_0_cpu_dm_agent_readdatavalid        --                    .readdatavalid
		);

	jtag_uart : component jtag_uart_cmp
		port map (
			clk            => clock_in_out_clk_clk,                                          --               clk.clk
			rst_n          => rst_controller_reset_out_reset_ports_inv,                      --             reset.reset_n
			av_chipselect  => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,      -- avalon_jtag_slave.chipselect
			av_address     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address(0),      --                  .address
			av_read_n      => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv,  --                  .read_n
			av_readdata    => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,        --                  .readdata
			av_write_n     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv, --                  .write_n
			av_writedata   => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,       --                  .writedata
			av_waitrequest => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest,     --                  .waitrequest
			av_irq         => irq_mapper_receiver0_irq                                       --               irq.irq
		);

	nvmm : component sys_nvmm_0_cmp
		port map (
			NVMM_alu_result => cpu_ci_custom0_alu_result, -- NVMM.alu_result
			NVMM_clk        => cpu_ci_custom0_clk,        --     .clk
			NVMM_ctrl       => cpu_ci_custom0_ctrl,       --     .ctrl
			NVMM_data0      => cpu_ci_custom0_data0,      --     .data0
			NVMM_data1      => cpu_ci_custom0_data1,      --     .data1
			NVMM_done       => cpu_ci_custom0_done,       --     .done
			NVMM_enable     => cpu_ci_custom0_enable,     --     .enable
			NVMM_reset      => cpu_ci_custom0_reset,      --     .reset
			NVMM_result     => cpu_ci_custom0_result      --     .result
		);

	ram : component sys_intel_onchip_memory_0_cmp
		port map (
			clk        => clock_in_out_clk_clk,                --   clk1.clk
			address    => mm_interconnect_0_ram_s1_address,    --     s1.address
			read       => mm_interconnect_0_ram_s1_read,       --       .read
			readdata   => mm_interconnect_0_ram_s1_readdata,   --       .readdata
			byteenable => mm_interconnect_0_ram_s1_byteenable, --       .byteenable
			write      => mm_interconnect_0_ram_s1_write,      --       .write
			writedata  => mm_interconnect_0_ram_s1_writedata,  --       .writedata
			reset      => rst_controller_reset_out_reset,      -- reset1.reset
			reset_req  => rst_controller_reset_out_reset_req   --       .reset_req
		);

	reset_in : component sys_reset_in_cmp
		port map (
			in_reset  => reset_reset,              --  in_reset.reset
			out_reset => reset_in_out_reset_reset  -- out_reset.reset
		);

	sysid_qsys_0 : component sys_sysid_qsys_0_cmp
		port map (
			clock    => clock_in_out_clk_clk,                                    --           clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv,                --         reset.reset_n
			readdata => mm_interconnect_0_sysid_qsys_0_control_slave_readdata,   -- control_slave.readdata
			address  => mm_interconnect_0_sysid_qsys_0_control_slave_address(0)  --              .address
		);

	mm_interconnect_0 : component sys_altera_mm_interconnect_1920_wvxmrgi_cmp
		port map (
			cpu_data_manager_awaddr                 => cpu_data_manager_awaddr,                                   --                cpu_data_manager.awaddr
			cpu_data_manager_awlen                  => cpu_data_manager_awlen,                                    --                                .awlen
			cpu_data_manager_awsize                 => cpu_data_manager_awsize,                                   --                                .awsize
			cpu_data_manager_awprot                 => cpu_data_manager_awprot,                                   --                                .awprot
			cpu_data_manager_awvalid                => cpu_data_manager_awvalid,                                  --                                .awvalid
			cpu_data_manager_awready                => cpu_data_manager_awready,                                  --                                .awready
			cpu_data_manager_wdata                  => cpu_data_manager_wdata,                                    --                                .wdata
			cpu_data_manager_wstrb                  => cpu_data_manager_wstrb,                                    --                                .wstrb
			cpu_data_manager_wlast                  => cpu_data_manager_wlast,                                    --                                .wlast
			cpu_data_manager_wvalid                 => cpu_data_manager_wvalid,                                   --                                .wvalid
			cpu_data_manager_wready                 => cpu_data_manager_wready,                                   --                                .wready
			cpu_data_manager_bresp                  => cpu_data_manager_bresp,                                    --                                .bresp
			cpu_data_manager_bvalid                 => cpu_data_manager_bvalid,                                   --                                .bvalid
			cpu_data_manager_bready                 => cpu_data_manager_bready,                                   --                                .bready
			cpu_data_manager_araddr                 => cpu_data_manager_araddr,                                   --                                .araddr
			cpu_data_manager_arlen                  => cpu_data_manager_arlen,                                    --                                .arlen
			cpu_data_manager_arsize                 => cpu_data_manager_arsize,                                   --                                .arsize
			cpu_data_manager_arprot                 => cpu_data_manager_arprot,                                   --                                .arprot
			cpu_data_manager_arvalid                => cpu_data_manager_arvalid,                                  --                                .arvalid
			cpu_data_manager_arready                => cpu_data_manager_arready,                                  --                                .arready
			cpu_data_manager_rdata                  => cpu_data_manager_rdata,                                    --                                .rdata
			cpu_data_manager_rresp                  => cpu_data_manager_rresp,                                    --                                .rresp
			cpu_data_manager_rlast                  => cpu_data_manager_rlast,                                    --                                .rlast
			cpu_data_manager_rvalid                 => cpu_data_manager_rvalid,                                   --                                .rvalid
			cpu_data_manager_rready                 => cpu_data_manager_rready,                                   --                                .rready
			cpu_instruction_manager_awaddr          => cpu_instruction_manager_awaddr,                            --         cpu_instruction_manager.awaddr
			cpu_instruction_manager_awlen           => cpu_instruction_manager_awlen,                             --                                .awlen
			cpu_instruction_manager_awsize          => cpu_instruction_manager_awsize,                            --                                .awsize
			cpu_instruction_manager_awburst         => cpu_instruction_manager_awburst,                           --                                .awburst
			cpu_instruction_manager_awprot          => cpu_instruction_manager_awprot,                            --                                .awprot
			cpu_instruction_manager_awvalid         => cpu_instruction_manager_awvalid,                           --                                .awvalid
			cpu_instruction_manager_awready         => cpu_instruction_manager_awready,                           --                                .awready
			cpu_instruction_manager_wdata           => cpu_instruction_manager_wdata,                             --                                .wdata
			cpu_instruction_manager_wstrb           => cpu_instruction_manager_wstrb,                             --                                .wstrb
			cpu_instruction_manager_wlast           => cpu_instruction_manager_wlast,                             --                                .wlast
			cpu_instruction_manager_wvalid          => cpu_instruction_manager_wvalid,                            --                                .wvalid
			cpu_instruction_manager_wready          => cpu_instruction_manager_wready,                            --                                .wready
			cpu_instruction_manager_bresp           => cpu_instruction_manager_bresp,                             --                                .bresp
			cpu_instruction_manager_bvalid          => cpu_instruction_manager_bvalid,                            --                                .bvalid
			cpu_instruction_manager_bready          => cpu_instruction_manager_bready,                            --                                .bready
			cpu_instruction_manager_araddr          => cpu_instruction_manager_araddr,                            --                                .araddr
			cpu_instruction_manager_arlen           => cpu_instruction_manager_arlen,                             --                                .arlen
			cpu_instruction_manager_arsize          => cpu_instruction_manager_arsize,                            --                                .arsize
			cpu_instruction_manager_arburst         => cpu_instruction_manager_arburst,                           --                                .arburst
			cpu_instruction_manager_arprot          => cpu_instruction_manager_arprot,                            --                                .arprot
			cpu_instruction_manager_arvalid         => cpu_instruction_manager_arvalid,                           --                                .arvalid
			cpu_instruction_manager_arready         => cpu_instruction_manager_arready,                           --                                .arready
			cpu_instruction_manager_rdata           => cpu_instruction_manager_rdata,                             --                                .rdata
			cpu_instruction_manager_rresp           => cpu_instruction_manager_rresp,                             --                                .rresp
			cpu_instruction_manager_rlast           => cpu_instruction_manager_rlast,                             --                                .rlast
			cpu_instruction_manager_rvalid          => cpu_instruction_manager_rvalid,                            --                                .rvalid
			cpu_instruction_manager_rready          => cpu_instruction_manager_rready,                            --                                .rready
			jtag_uart_avalon_jtag_slave_address     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address,     --     jtag_uart_avalon_jtag_slave.address
			jtag_uart_avalon_jtag_slave_write       => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write,       --                                .write
			jtag_uart_avalon_jtag_slave_read        => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read,        --                                .read
			jtag_uart_avalon_jtag_slave_readdata    => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,    --                                .readdata
			jtag_uart_avalon_jtag_slave_writedata   => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,   --                                .writedata
			jtag_uart_avalon_jtag_slave_waitrequest => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest, --                                .waitrequest
			jtag_uart_avalon_jtag_slave_chipselect  => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,  --                                .chipselect
			sysid_qsys_0_control_slave_address      => mm_interconnect_0_sysid_qsys_0_control_slave_address,      --      sysid_qsys_0_control_slave.address
			sysid_qsys_0_control_slave_readdata     => mm_interconnect_0_sysid_qsys_0_control_slave_readdata,     --                                .readdata
			cpu_dm_agent_address                    => mm_interconnect_0_cpu_dm_agent_address,                    --                    cpu_dm_agent.address
			cpu_dm_agent_write                      => mm_interconnect_0_cpu_dm_agent_write,                      --                                .write
			cpu_dm_agent_read                       => mm_interconnect_0_cpu_dm_agent_read,                       --                                .read
			cpu_dm_agent_readdata                   => mm_interconnect_0_cpu_dm_agent_readdata,                   --                                .readdata
			cpu_dm_agent_writedata                  => mm_interconnect_0_cpu_dm_agent_writedata,                  --                                .writedata
			cpu_dm_agent_readdatavalid              => mm_interconnect_0_cpu_dm_agent_readdatavalid,              --                                .readdatavalid
			cpu_dm_agent_waitrequest                => mm_interconnect_0_cpu_dm_agent_waitrequest,                --                                .waitrequest
			ram_s1_address                          => mm_interconnect_0_ram_s1_address,                          --                          ram_s1.address
			ram_s1_write                            => mm_interconnect_0_ram_s1_write,                            --                                .write
			ram_s1_read                             => mm_interconnect_0_ram_s1_read,                             --                                .read
			ram_s1_readdata                         => mm_interconnect_0_ram_s1_readdata,                         --                                .readdata
			ram_s1_writedata                        => mm_interconnect_0_ram_s1_writedata,                        --                                .writedata
			ram_s1_byteenable                       => mm_interconnect_0_ram_s1_byteenable,                       --                                .byteenable
			cpu_timer_sw_agent_address              => mm_interconnect_0_cpu_timer_sw_agent_address,              --              cpu_timer_sw_agent.address
			cpu_timer_sw_agent_write                => mm_interconnect_0_cpu_timer_sw_agent_write,                --                                .write
			cpu_timer_sw_agent_read                 => mm_interconnect_0_cpu_timer_sw_agent_read,                 --                                .read
			cpu_timer_sw_agent_readdata             => mm_interconnect_0_cpu_timer_sw_agent_readdata,             --                                .readdata
			cpu_timer_sw_agent_writedata            => mm_interconnect_0_cpu_timer_sw_agent_writedata,            --                                .writedata
			cpu_timer_sw_agent_byteenable           => mm_interconnect_0_cpu_timer_sw_agent_byteenable,           --                                .byteenable
			cpu_timer_sw_agent_readdatavalid        => mm_interconnect_0_cpu_timer_sw_agent_readdatavalid,        --                                .readdatavalid
			cpu_timer_sw_agent_waitrequest          => mm_interconnect_0_cpu_timer_sw_agent_waitrequest,          --                                .waitrequest
			cpu_reset_reset_bridge_in_reset_reset   => rst_controller_reset_out_reset,                            -- cpu_reset_reset_bridge_in_reset.reset
			clock_in_out_clk_clk                    => clock_in_out_clk_clk                                       --                clock_in_out_clk.clk
		);

	irq_mapper : component sys_altera_irq_mapper_2001_ghcid5i_cmp
		port map (
			clk           => clock_in_out_clk_clk,           --       clk.clk
			reset         => rst_controller_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_receiver0_irq,       -- receiver0.irq
			sender_irq    => cpu_platform_irq_rx_irq         --    sender.irq
		);

	rst_controller : component altera_reset_controller_cmp
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 1,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_in_out_reset_reset,           -- reset_in0.reset
			clk            => clock_in_out_clk_clk,               --       clk.clk
			reset_out      => rst_controller_reset_out_reset,     -- reset_out.reset
			reset_req      => rst_controller_reset_out_reset_req, --          .reset_req
			reset_req_in0  => '0',                                -- (terminated)
			reset_in1      => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;

	rst_controller_reset_out_reset_ports_inv <= not rst_controller_reset_out_reset;

end architecture rtl; -- of sys
