// NoisSys.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module NoisSys (
		input  wire  clk_clk,     //   clk.clk
		input  wire  reset_reset  // reset.reset
	);

	wire    clock_in_out_clk_clk; // clock_in:out_clk -> reset_in:clk

	NoisSys_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	NoisSys_reset_in reset_in (
		.clk       (clock_in_out_clk_clk), //   input,  width = 1,       clk.clk
		.in_reset  (reset_reset),          //   input,  width = 1,  in_reset.reset
		.out_reset ()                      //  output,  width = 1, out_reset.reset
	);

endmodule
