-- sys_intel_onchip_memory_0.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library intel_onchip_memory_148;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys_intel_onchip_memory_0 is
	port (
		clk        : in  std_logic                     := '0';             --   clk1.clk
		address    : in  std_logic_vector(19 downto 0) := (others => '0'); --     s1.address
		read       : in  std_logic                     := '0';             --       .read
		readdata   : out std_logic_vector(31 downto 0);                    --       .readdata
		byteenable : in  std_logic_vector(3 downto 0)  := (others => '0'); --       .byteenable
		write      : in  std_logic                     := '0';             --       .write
		writedata  : in  std_logic_vector(31 downto 0) := (others => '0'); --       .writedata
		reset      : in  std_logic                     := '0';             -- reset1.reset
		reset_req  : in  std_logic                     := '0'              --       .reset_req
	);
end entity sys_intel_onchip_memory_0;

architecture rtl of sys_intel_onchip_memory_0 is
	component sys_intel_onchip_memory_0_intel_onchip_memory_148_55zpfxi_cmp is
		generic (
			INIT_FILE : string := ""
		);
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(19 downto 0) := (others => 'X'); -- address
			read       : in  std_logic                     := 'X';             -- read
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			write      : in  std_logic                     := 'X';             -- write
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X'              -- reset_req
		);
	end component sys_intel_onchip_memory_0_intel_onchip_memory_148_55zpfxi_cmp;

	for intel_onchip_memory_0 : sys_intel_onchip_memory_0_intel_onchip_memory_148_55zpfxi_cmp
		use entity intel_onchip_memory_148.sys_intel_onchip_memory_0_intel_onchip_memory_148_55zpfxi;
begin

	intel_onchip_memory_0 : component sys_intel_onchip_memory_0_intel_onchip_memory_148_55zpfxi_cmp
		generic map (
			INIT_FILE => "sys_intel_onchip_memory_0_intel_onchip_memory_0.hex"
		)
		port map (
			clk        => clk,        --   clk1.clk
			address    => address,    --     s1.address
			read       => read,       --       .read
			readdata   => readdata,   --       .readdata
			byteenable => byteenable, --       .byteenable
			write      => write,      --       .write
			writedata  => writedata,  --       .writedata
			reset      => reset,      -- reset1.reset
			reset_req  => reset_req   --       .reset_req
		);

end architecture rtl; -- of sys_intel_onchip_memory_0
