-- cpu.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library intel_niosv_g_220;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cpu is
	port (
		clk                          : in  std_logic                     := '0';             --                 clk.clk,           Clock Input
		reset_reset                  : in  std_logic                     := '0';             --               reset.reset,         Reset Input
		platform_irq_rx_irq          : in  std_logic_vector(15 downto 0) := (others => '0'); --     platform_irq_rx.irq,           Level-sensitive interrupt request lines.
		instruction_manager_awaddr   : out std_logic_vector(31 downto 0);                    -- instruction_manager.awaddr,        Write Address Channel -- Write Address. This is unused.
		instruction_manager_awlen    : out std_logic_vector(7 downto 0);                     --                    .awlen,         Write Address Channel -- Burst Length. This is unused.
		instruction_manager_awsize   : out std_logic_vector(2 downto 0);                     --                    .awsize,        Write Address Channel -- Burst Size. This is unused.
		instruction_manager_awburst  : out std_logic_vector(1 downto 0);                     --                    .awburst,       Write Address Channel -- Burst Type. This is unused.
		instruction_manager_awprot   : out std_logic_vector(2 downto 0);                     --                    .awprot,        Write Address Channel -- Protection Type. This is unused.
		instruction_manager_awvalid  : out std_logic;                                        --                    .awvalid,       Write Address Channel -- Write Address Valid. This is unused.
		instruction_manager_awready  : in  std_logic                     := '0';             --                    .awready,       Write Address Channel -- Write Address Ready. This is unused.
		instruction_manager_wdata    : out std_logic_vector(31 downto 0);                    --                    .wdata,         Write Data Channel -- Write Data. This is unused.
		instruction_manager_wstrb    : out std_logic_vector(3 downto 0);                     --                    .wstrb,         Write Data Channel -- Write Strobes. This is unused.
		instruction_manager_wlast    : out std_logic;                                        --                    .wlast,         Write Data Channel -- Write Last. This is unused.
		instruction_manager_wvalid   : out std_logic;                                        --                    .wvalid,        Write Data Channel -- Write Valid. This is unused.
		instruction_manager_wready   : in  std_logic                     := '0';             --                    .wready,        Write Data Channel -- Write Ready. This is unused.
		instruction_manager_bresp    : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .bresp,         Write Response Channel -- Write Response. This is unused.
		instruction_manager_bvalid   : in  std_logic                     := '0';             --                    .bvalid,        Write Response Channel -- Write Response Valid. This is unused.
		instruction_manager_bready   : out std_logic;                                        --                    .bready,        Write Response Channel -- Write Response Ready. This is unused.
		instruction_manager_araddr   : out std_logic_vector(31 downto 0);                    --                    .araddr,        Read Address Channel -- Read Address. Instruction address (program counter).
		instruction_manager_arlen    : out std_logic_vector(7 downto 0);                     --                    .arlen,         Read Address Channel -- Burst Length. 0 for peripheral region access, 7 for cacheable region access.
		instruction_manager_arsize   : out std_logic_vector(2 downto 0);                     --                    .arsize,        Read Address Channel -- Burst Size. This is tied to 2 (4 byte burst size).
		instruction_manager_arburst  : out std_logic_vector(1 downto 0);                     --                    .arburst,       Read Address Channel -- Burst Type. This is tied to 2 (WRAP burst type).
		instruction_manager_arprot   : out std_logic_vector(2 downto 0);                     --                    .arprot,        Read Address Channel -- Protection Type. This is unused.
		instruction_manager_arvalid  : out std_logic;                                        --                    .arvalid,       Read Address Channel -- Read Address Valid. Instruction address valid.
		instruction_manager_arready  : in  std_logic                     := '0';             --                    .arready,       Read Address Channel -- Read Address Ready. Instruction address ready (from memory).
		instruction_manager_rdata    : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .rdata,         Read Data Channel -- Read Data. Instruction word.
		instruction_manager_rresp    : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .rresp,         Read Data Channel -- Read Response. Instruction response. A non-zero value indicates an instruction access fault exception.
		instruction_manager_rlast    : in  std_logic                     := '0';             --                    .rlast,         Read Data Channel -- Read Last. Last transfer in the read burst.
		instruction_manager_rvalid   : in  std_logic                     := '0';             --                    .rvalid,        Read Data Channel -- Read Valid. Instruction valid.
		instruction_manager_rready   : out std_logic;                                        --                    .rready,        Read Data Channel -- Read Ready. This is tied high since the core is always ready to receive an instruction.
		data_manager_awaddr          : out std_logic_vector(31 downto 0);                    --        data_manager.awaddr,        Write Address Channel -- Write Address. Store address.
		data_manager_awlen           : out std_logic_vector(7 downto 0);                     --                    .awlen,         Write Address Channel -- Burst Length. 0 for peripheral region access, 7 for cacheable region access.
		data_manager_awsize          : out std_logic_vector(2 downto 0);                     --                    .awsize,        Write Address Channel -- Burst Size. Store size (SB, SH, or SW).
		data_manager_awprot          : out std_logic_vector(2 downto 0);                     --                    .awprot,        Write Address Channel -- Protection Type. This is unused.
		data_manager_awvalid         : out std_logic;                                        --                    .awvalid,       Write Address Channel -- Write Address Valid. Store address valid.
		data_manager_awready         : in  std_logic                     := '0';             --                    .awready,       Write Address Channel -- Write Address Ready. Store address ready (from memory).
		data_manager_wdata           : out std_logic_vector(31 downto 0);                    --                    .wdata,         Write Data Channel -- Write Data. Store data.
		data_manager_wstrb           : out std_logic_vector(3 downto 0);                     --                    .wstrb,         Write Data Channel -- Write Strobes. Byte position in word.
		data_manager_wlast           : out std_logic;                                        --                    .wlast,         Write Data Channel -- Write Last. Last transfer in the write burst.
		data_manager_wvalid          : out std_logic;                                        --                    .wvalid,        Write Data Channel -- Write Valid. Store data valid.
		data_manager_wready          : in  std_logic                     := '0';             --                    .wready,        Write Data Channel -- Write Ready. Store data ready (from memory).
		data_manager_bresp           : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .bresp,         Write Response Channel -- Write Response. Store response. A non-zero value indicates a store access fault exception.
		data_manager_bvalid          : in  std_logic                     := '0';             --                    .bvalid,        Write Response Channel -- Write Response Valid. Store response valid.
		data_manager_bready          : out std_logic;                                        --                    .bready,        Write Response Channel -- Write Response Ready. This is tied high since the core is always ready to receive a store response.
		data_manager_araddr          : out std_logic_vector(31 downto 0);                    --                    .araddr,        Read Address Channel -- Read Address. Load address.
		data_manager_arlen           : out std_logic_vector(7 downto 0);                     --                    .arlen,         Read Address Channel -- Burst Length. 0 for peripheral region access, 7 for cacheable region access.
		data_manager_arsize          : out std_logic_vector(2 downto 0);                     --                    .arsize,        Read Address Channel -- Burst Size. Load size (LB, LH, or LW).
		data_manager_arprot          : out std_logic_vector(2 downto 0);                     --                    .arprot,        Read Address Channel -- Protection Type. This is unused.
		data_manager_arvalid         : out std_logic;                                        --                    .arvalid,       Read Address Channel -- Read Address Valid. Load address valid.
		data_manager_arready         : in  std_logic                     := '0';             --                    .arready,       Read Address Channel -- Read Address Ready. Load address ready (from agents).
		data_manager_rdata           : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .rdata,         Read Data Channel -- Read Data. Load data.
		data_manager_rresp           : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .rresp,         Read Data Channel -- Read Response. Load response. A non-zero value indicates a load access fault exception.
		data_manager_rlast           : in  std_logic                     := '0';             --                    .rlast,         Read Data Channel -- Read Last. Last transfer in the read burst.
		data_manager_rvalid          : in  std_logic                     := '0';             --                    .rvalid,        Read Data Channel -- Read Valid. Load data valid.
		data_manager_rready          : out std_logic;                                        --                    .rready,        Read Data Channel -- Read Ready. This is tied high since the core is always ready to receive the load data.
		ci_custom0_clk               : out std_logic;                                        --          ci_custom0.clk
		ci_custom0_reset             : out std_logic;                                        --                    .reset
		ci_custom0_data0             : out std_logic_vector(31 downto 0);                    --                    .data0
		ci_custom0_data1             : out std_logic_vector(31 downto 0);                    --                    .data1
		ci_custom0_ctrl              : out std_logic_vector(31 downto 0);                    --                    .ctrl
		ci_custom0_alu_result        : out std_logic_vector(31 downto 0);                    --                    .alu_result
		ci_custom0_enable            : out std_logic;                                        --                    .enable
		ci_custom0_result            : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .result
		ci_custom0_done              : in  std_logic                     := '0';             --                    .done
		timer_sw_agent_address       : in  std_logic_vector(5 downto 0)  := (others => '0'); --      timer_sw_agent.address,       The address in the Timer and Software Interrupt Module that the core wants to write to or read from. This is relative to the Timer and Software Interrupt Module base address.
		timer_sw_agent_byteenable    : in  std_logic_vector(3 downto 0)  := (others => '0'); --                    .byteenable,    Store byte enable.
		timer_sw_agent_read          : in  std_logic                     := '0';             --                    .read,          Indicates if the core wants to load from "timer_sw_agent_address" in the Timer and Software Interrupt Module.
		timer_sw_agent_readdata      : out std_logic_vector(31 downto 0);                    --                    .readdata,      Load data from the Timer and Software Interrupt Module sent to the core.
		timer_sw_agent_write         : in  std_logic                     := '0';             --                    .write,         Indicates if the core wants to store to "timer_sw_agent_address" in the Timer and Software Interrupt Module.
		timer_sw_agent_writedata     : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .writedata,     Store data to the Timer and Software Interrupt Module sent from the core.
		timer_sw_agent_waitrequest   : out std_logic;                                        --                    .waitrequest,   Timer and Software Interrupt Module not ready to receive write or read request from the core.
		timer_sw_agent_readdatavalid : out std_logic;                                        --                    .readdatavalid, Load data valid.
		dm_agent_address             : in  std_logic_vector(15 downto 0) := (others => '0'); --            dm_agent.address,       The address in the Debug Module that the core wants to write to or read from. This is relative to the Debug Module base address.
		dm_agent_read                : in  std_logic                     := '0';             --                    .read,          Indicates if the core wants to load from "dm_agent_address" in the Debug Module.
		dm_agent_readdata            : out std_logic_vector(31 downto 0);                    --                    .readdata,      Load data from the Debug Module sent to the core.
		dm_agent_write               : in  std_logic                     := '0';             --                    .write,         Indicates if the core wants to store to "dm_agent_address" in the Debug Module.
		dm_agent_writedata           : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .writedata,     Store data to the Debug Module sent from the core.
		dm_agent_waitrequest         : out std_logic;                                        --                    .waitrequest,   Debug Module not ready to receive write or read request from the core.
		dm_agent_readdatavalid       : out std_logic                                         --                    .readdatavalid, Load data valid.
	);
end entity cpu;

architecture rtl of cpu is
	component cpu_intel_niosv_g_220_jwf5evi_cmp is
		port (
			clk                          : in  std_logic                     := 'X';             -- clk
			reset_reset                  : in  std_logic                     := 'X';             -- reset
			platform_irq_rx_irq          : in  std_logic_vector(15 downto 0) := (others => 'X'); -- irq
			instruction_manager_awaddr   : out std_logic_vector(31 downto 0);                    -- awaddr
			instruction_manager_awlen    : out std_logic_vector(7 downto 0);                     -- awlen
			instruction_manager_awsize   : out std_logic_vector(2 downto 0);                     -- awsize
			instruction_manager_awburst  : out std_logic_vector(1 downto 0);                     -- awburst
			instruction_manager_awprot   : out std_logic_vector(2 downto 0);                     -- awprot
			instruction_manager_awvalid  : out std_logic;                                        -- awvalid
			instruction_manager_awready  : in  std_logic                     := 'X';             -- awready
			instruction_manager_wdata    : out std_logic_vector(31 downto 0);                    -- wdata
			instruction_manager_wstrb    : out std_logic_vector(3 downto 0);                     -- wstrb
			instruction_manager_wlast    : out std_logic;                                        -- wlast
			instruction_manager_wvalid   : out std_logic;                                        -- wvalid
			instruction_manager_wready   : in  std_logic                     := 'X';             -- wready
			instruction_manager_bresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			instruction_manager_bvalid   : in  std_logic                     := 'X';             -- bvalid
			instruction_manager_bready   : out std_logic;                                        -- bready
			instruction_manager_araddr   : out std_logic_vector(31 downto 0);                    -- araddr
			instruction_manager_arlen    : out std_logic_vector(7 downto 0);                     -- arlen
			instruction_manager_arsize   : out std_logic_vector(2 downto 0);                     -- arsize
			instruction_manager_arburst  : out std_logic_vector(1 downto 0);                     -- arburst
			instruction_manager_arprot   : out std_logic_vector(2 downto 0);                     -- arprot
			instruction_manager_arvalid  : out std_logic;                                        -- arvalid
			instruction_manager_arready  : in  std_logic                     := 'X';             -- arready
			instruction_manager_rdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			instruction_manager_rresp    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			instruction_manager_rlast    : in  std_logic                     := 'X';             -- rlast
			instruction_manager_rvalid   : in  std_logic                     := 'X';             -- rvalid
			instruction_manager_rready   : out std_logic;                                        -- rready
			data_manager_awaddr          : out std_logic_vector(31 downto 0);                    -- awaddr
			data_manager_awlen           : out std_logic_vector(7 downto 0);                     -- awlen
			data_manager_awsize          : out std_logic_vector(2 downto 0);                     -- awsize
			data_manager_awprot          : out std_logic_vector(2 downto 0);                     -- awprot
			data_manager_awvalid         : out std_logic;                                        -- awvalid
			data_manager_awready         : in  std_logic                     := 'X';             -- awready
			data_manager_wdata           : out std_logic_vector(31 downto 0);                    -- wdata
			data_manager_wstrb           : out std_logic_vector(3 downto 0);                     -- wstrb
			data_manager_wlast           : out std_logic;                                        -- wlast
			data_manager_wvalid          : out std_logic;                                        -- wvalid
			data_manager_wready          : in  std_logic                     := 'X';             -- wready
			data_manager_bresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			data_manager_bvalid          : in  std_logic                     := 'X';             -- bvalid
			data_manager_bready          : out std_logic;                                        -- bready
			data_manager_araddr          : out std_logic_vector(31 downto 0);                    -- araddr
			data_manager_arlen           : out std_logic_vector(7 downto 0);                     -- arlen
			data_manager_arsize          : out std_logic_vector(2 downto 0);                     -- arsize
			data_manager_arprot          : out std_logic_vector(2 downto 0);                     -- arprot
			data_manager_arvalid         : out std_logic;                                        -- arvalid
			data_manager_arready         : in  std_logic                     := 'X';             -- arready
			data_manager_rdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			data_manager_rresp           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			data_manager_rlast           : in  std_logic                     := 'X';             -- rlast
			data_manager_rvalid          : in  std_logic                     := 'X';             -- rvalid
			data_manager_rready          : out std_logic;                                        -- rready
			ci_custom0_clk               : out std_logic;                                        -- clk
			ci_custom0_reset             : out std_logic;                                        -- reset
			ci_custom0_data0             : out std_logic_vector(31 downto 0);                    -- data0
			ci_custom0_data1             : out std_logic_vector(31 downto 0);                    -- data1
			ci_custom0_ctrl              : out std_logic_vector(31 downto 0);                    -- ctrl
			ci_custom0_alu_result        : out std_logic_vector(31 downto 0);                    -- alu_result
			ci_custom0_enable            : out std_logic;                                        -- enable
			ci_custom0_result            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- result
			ci_custom0_done              : in  std_logic                     := 'X';             -- done
			timer_sw_agent_address       : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- address
			timer_sw_agent_byteenable    : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			timer_sw_agent_read          : in  std_logic                     := 'X';             -- read
			timer_sw_agent_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			timer_sw_agent_write         : in  std_logic                     := 'X';             -- write
			timer_sw_agent_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			timer_sw_agent_waitrequest   : out std_logic;                                        -- waitrequest
			timer_sw_agent_readdatavalid : out std_logic;                                        -- readdatavalid
			dm_agent_address             : in  std_logic_vector(15 downto 0) := (others => 'X'); -- address
			dm_agent_read                : in  std_logic                     := 'X';             -- read
			dm_agent_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			dm_agent_write               : in  std_logic                     := 'X';             -- write
			dm_agent_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			dm_agent_waitrequest         : out std_logic;                                        -- waitrequest
			dm_agent_readdatavalid       : out std_logic                                         -- readdatavalid
		);
	end component cpu_intel_niosv_g_220_jwf5evi_cmp;

	for intel_niosv_g_inst : cpu_intel_niosv_g_220_jwf5evi_cmp
		use entity intel_niosv_g_220.cpu_intel_niosv_g_220_jwf5evi;
begin

	intel_niosv_g_inst : component cpu_intel_niosv_g_220_jwf5evi_cmp
		port map (
			clk                          => clk,                          --                 clk.clk
			reset_reset                  => reset_reset,                  --               reset.reset
			platform_irq_rx_irq          => platform_irq_rx_irq,          --     platform_irq_rx.irq
			instruction_manager_awaddr   => instruction_manager_awaddr,   -- instruction_manager.awaddr
			instruction_manager_awlen    => instruction_manager_awlen,    --                    .awlen
			instruction_manager_awsize   => instruction_manager_awsize,   --                    .awsize
			instruction_manager_awburst  => instruction_manager_awburst,  --                    .awburst
			instruction_manager_awprot   => instruction_manager_awprot,   --                    .awprot
			instruction_manager_awvalid  => instruction_manager_awvalid,  --                    .awvalid
			instruction_manager_awready  => instruction_manager_awready,  --                    .awready
			instruction_manager_wdata    => instruction_manager_wdata,    --                    .wdata
			instruction_manager_wstrb    => instruction_manager_wstrb,    --                    .wstrb
			instruction_manager_wlast    => instruction_manager_wlast,    --                    .wlast
			instruction_manager_wvalid   => instruction_manager_wvalid,   --                    .wvalid
			instruction_manager_wready   => instruction_manager_wready,   --                    .wready
			instruction_manager_bresp    => instruction_manager_bresp,    --                    .bresp
			instruction_manager_bvalid   => instruction_manager_bvalid,   --                    .bvalid
			instruction_manager_bready   => instruction_manager_bready,   --                    .bready
			instruction_manager_araddr   => instruction_manager_araddr,   --                    .araddr
			instruction_manager_arlen    => instruction_manager_arlen,    --                    .arlen
			instruction_manager_arsize   => instruction_manager_arsize,   --                    .arsize
			instruction_manager_arburst  => instruction_manager_arburst,  --                    .arburst
			instruction_manager_arprot   => instruction_manager_arprot,   --                    .arprot
			instruction_manager_arvalid  => instruction_manager_arvalid,  --                    .arvalid
			instruction_manager_arready  => instruction_manager_arready,  --                    .arready
			instruction_manager_rdata    => instruction_manager_rdata,    --                    .rdata
			instruction_manager_rresp    => instruction_manager_rresp,    --                    .rresp
			instruction_manager_rlast    => instruction_manager_rlast,    --                    .rlast
			instruction_manager_rvalid   => instruction_manager_rvalid,   --                    .rvalid
			instruction_manager_rready   => instruction_manager_rready,   --                    .rready
			data_manager_awaddr          => data_manager_awaddr,          --        data_manager.awaddr
			data_manager_awlen           => data_manager_awlen,           --                    .awlen
			data_manager_awsize          => data_manager_awsize,          --                    .awsize
			data_manager_awprot          => data_manager_awprot,          --                    .awprot
			data_manager_awvalid         => data_manager_awvalid,         --                    .awvalid
			data_manager_awready         => data_manager_awready,         --                    .awready
			data_manager_wdata           => data_manager_wdata,           --                    .wdata
			data_manager_wstrb           => data_manager_wstrb,           --                    .wstrb
			data_manager_wlast           => data_manager_wlast,           --                    .wlast
			data_manager_wvalid          => data_manager_wvalid,          --                    .wvalid
			data_manager_wready          => data_manager_wready,          --                    .wready
			data_manager_bresp           => data_manager_bresp,           --                    .bresp
			data_manager_bvalid          => data_manager_bvalid,          --                    .bvalid
			data_manager_bready          => data_manager_bready,          --                    .bready
			data_manager_araddr          => data_manager_araddr,          --                    .araddr
			data_manager_arlen           => data_manager_arlen,           --                    .arlen
			data_manager_arsize          => data_manager_arsize,          --                    .arsize
			data_manager_arprot          => data_manager_arprot,          --                    .arprot
			data_manager_arvalid         => data_manager_arvalid,         --                    .arvalid
			data_manager_arready         => data_manager_arready,         --                    .arready
			data_manager_rdata           => data_manager_rdata,           --                    .rdata
			data_manager_rresp           => data_manager_rresp,           --                    .rresp
			data_manager_rlast           => data_manager_rlast,           --                    .rlast
			data_manager_rvalid          => data_manager_rvalid,          --                    .rvalid
			data_manager_rready          => data_manager_rready,          --                    .rready
			ci_custom0_clk               => ci_custom0_clk,               --          ci_custom0.clk
			ci_custom0_reset             => ci_custom0_reset,             --                    .reset
			ci_custom0_data0             => ci_custom0_data0,             --                    .data0
			ci_custom0_data1             => ci_custom0_data1,             --                    .data1
			ci_custom0_ctrl              => ci_custom0_ctrl,              --                    .ctrl
			ci_custom0_alu_result        => ci_custom0_alu_result,        --                    .alu_result
			ci_custom0_enable            => ci_custom0_enable,            --                    .enable
			ci_custom0_result            => ci_custom0_result,            --                    .result
			ci_custom0_done              => ci_custom0_done,              --                    .done
			timer_sw_agent_address       => timer_sw_agent_address,       --      timer_sw_agent.address
			timer_sw_agent_byteenable    => timer_sw_agent_byteenable,    --                    .byteenable
			timer_sw_agent_read          => timer_sw_agent_read,          --                    .read
			timer_sw_agent_readdata      => timer_sw_agent_readdata,      --                    .readdata
			timer_sw_agent_write         => timer_sw_agent_write,         --                    .write
			timer_sw_agent_writedata     => timer_sw_agent_writedata,     --                    .writedata
			timer_sw_agent_waitrequest   => timer_sw_agent_waitrequest,   --                    .waitrequest
			timer_sw_agent_readdatavalid => timer_sw_agent_readdatavalid, --                    .readdatavalid
			dm_agent_address             => dm_agent_address,             --            dm_agent.address
			dm_agent_read                => dm_agent_read,                --                    .read
			dm_agent_readdata            => dm_agent_readdata,            --                    .readdata
			dm_agent_write               => dm_agent_write,               --                    .write
			dm_agent_writedata           => dm_agent_writedata,           --                    .writedata
			dm_agent_waitrequest         => dm_agent_waitrequest,         --                    .waitrequest
			dm_agent_readdatavalid       => dm_agent_readdatavalid        --                    .readdatavalid
		);

end architecture rtl; -- of cpu
