// sys_clock_in.v

// Generated using ACDS version 24.1 106

`timescale 1 ps / 1 ps
module sys_clock_in (
		input  wire  in_clk,  //  in_clk.clk, Clock Input
		output wire  out_clk  // out_clk.clk, Clock Output
	);

	assign out_clk = in_clk;

endmodule
