# TCL File Generated by Component Editor 24.1
# Wed Aug 20 18:28:00 NZST 2025
# DO NOT MODIFY


# 
# nvmm "nvmm" v1.0
#  2025.08.20.18:28:00
# 
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module nvmm
# 
set_module_property DESCRIPTION ""
set_module_property NAME nvmm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME nvmm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL nvmm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file nvmm3.vhd VHDL PATH nvmm3.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter N INTEGER 25
set_parameter_property N DEFAULT_VALUE 25
set_parameter_property N DISPLAY_NAME N
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES -2147483648:2147483647
set_parameter_property N AFFECTS_GENERATION false
set_parameter_property N HDL_PARAMETER true
set_parameter_property N EXPORT true
add_parameter K INTEGER 5
set_parameter_property K DEFAULT_VALUE 5
set_parameter_property K DISPLAY_NAME K
set_parameter_property K UNITS None
set_parameter_property K ALLOWED_RANGES -2147483648:2147483647
set_parameter_property K AFFECTS_GENERATION false
set_parameter_property K HDL_PARAMETER true
set_parameter_property K EXPORT true


# 
# display items
# 


# 
# connection point NVMM
# 
add_interface NVMM niosv_custom_instruction end
set_interface_property NVMM ENABLED true
set_interface_property NVMM EXPORT_OF ""
set_interface_property NVMM PORT_NAME_MAP ""
set_interface_property NVMM CMSIS_SVD_VARIABLES ""
set_interface_property NVMM SVD_ADDRESS_GROUP ""
set_interface_property NVMM IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property NVMM SV_INTERFACE_TYPE ""
set_interface_property NVMM SV_INTERFACE_MODPORT_TYPE ""

add_interface_port NVMM NVMM_alu_result alu_result Input 32
add_interface_port NVMM NVMM_clk clk Input 1
add_interface_port NVMM NVMM_ctrl ctrl Input 32
add_interface_port NVMM NVMM_data0 data0 Input 32
add_interface_port NVMM NVMM_data1 data1 Input 32
add_interface_port NVMM NVMM_done done Output 1
add_interface_port NVMM NVMM_enable enable Input 1
add_interface_port NVMM NVMM_reset reset Input 1
add_interface_port NVMM NVMM_result result Output 32

