-- sys_clock_in.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys_clock_in is
	port (
		in_clk  : in  std_logic := '0'; --  in_clk.clk, Clock Input
		out_clk : out std_logic         -- out_clk.clk, Clock Output
	);
end entity sys_clock_in;

architecture rtl of sys_clock_in is
begin

	out_clk <= in_clk;

end architecture rtl; -- of sys_clock_in
