-- sys_sysid_qsys_0.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library altera_avalon_sysid_qsys_1916;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys_sysid_qsys_0 is
	port (
		clock    : in  std_logic                     := '0'; --           clk.clk
		reset_n  : in  std_logic                     := '0'; --         reset.reset_n
		readdata : out std_logic_vector(31 downto 0);        -- control_slave.readdata
		address  : in  std_logic                     := '0'  --              .address
	);
end entity sys_sysid_qsys_0;

architecture rtl of sys_sysid_qsys_0 is
	component altera_avalon_sysid_qsys_cmp is
		generic (
			ID_VALUE  : integer := 0;
			TIMESTAMP : integer := 0
		);
		port (
			clock    : in  std_logic                     := 'X'; -- clk
			reset_n  : in  std_logic                     := 'X'; -- reset_n
			readdata : out std_logic_vector(31 downto 0);        -- readdata
			address  : in  std_logic                     := 'X'  -- address
		);
	end component altera_avalon_sysid_qsys_cmp;

	for sysid_qsys_0 : altera_avalon_sysid_qsys_cmp
		use entity altera_avalon_sysid_qsys_1916.altera_avalon_sysid_qsys;
begin

	sysid_qsys_0 : component altera_avalon_sysid_qsys_cmp
		generic map (
			ID_VALUE  => 9,
			TIMESTAMP => 0
		)
		port map (
			clock    => clock,    --           clk.clk
			reset_n  => reset_n,  --         reset.reset_n
			readdata => readdata, -- control_slave.readdata
			address  => address   --              .address
		);

end architecture rtl; -- of sys_sysid_qsys_0
