-- sys_nvmm_0.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library nvmm_10;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys_nvmm_0 is
	generic (
		N : integer := 4
	);
	port (
		NVMM_alu_result : in  std_logic_vector(31 downto 0) := (others => '0'); -- NVMM.alu_result
		NVMM_clk        : in  std_logic                     := '0';             --     .clk
		NVMM_ctrl       : in  std_logic_vector(31 downto 0) := (others => '0'); --     .ctrl
		NVMM_data0      : in  std_logic_vector(31 downto 0) := (others => '0'); --     .data0
		NVMM_data1      : in  std_logic_vector(31 downto 0) := (others => '0'); --     .data1
		NVMM_done       : out std_logic;                                        --     .done
		NVMM_enable     : in  std_logic                     := '0';             --     .enable
		NVMM_reset      : in  std_logic                     := '0';             --     .reset
		NVMM_result     : out std_logic_vector(31 downto 0)                     --     .result
	);
end entity sys_nvmm_0;

architecture rtl of sys_nvmm_0 is
	component nvmm_cmp is
		generic (
			N : integer := 4
		);
		port (
			NVMM_alu_result : in  std_logic_vector(31 downto 0) := (others => 'X'); -- alu_result
			NVMM_clk        : in  std_logic                     := 'X';             -- clk
			NVMM_ctrl       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- ctrl
			NVMM_data0      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data0
			NVMM_data1      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- data1
			NVMM_done       : out std_logic;                                        -- done
			NVMM_enable     : in  std_logic                     := 'X';             -- enable
			NVMM_reset      : in  std_logic                     := 'X';             -- reset
			NVMM_result     : out std_logic_vector(31 downto 0)                     -- result
		);
	end component nvmm_cmp;

	for nvmm_0 : nvmm_cmp
		use entity nvmm_10.nvmm;
begin

	nvmm_0 : component nvmm_cmp
		generic map (
			N => N
		)
		port map (
			NVMM_alu_result => NVMM_alu_result, -- NVMM.alu_result
			NVMM_clk        => NVMM_clk,        --     .clk
			NVMM_ctrl       => NVMM_ctrl,       --     .ctrl
			NVMM_data0      => NVMM_data0,      --     .data0
			NVMM_data1      => NVMM_data1,      --     .data1
			NVMM_done       => NVMM_done,       --     .done
			NVMM_enable     => NVMM_enable,     --     .enable
			NVMM_reset      => NVMM_reset,      --     .reset
			NVMM_result     => NVMM_result      --     .result
		);

end architecture rtl; -- of sys_nvmm_0
