// sys_reset_in.v

// Generated using ACDS version 24.1 106

`timescale 1 ps / 1 ps
module sys_reset_in (
		input  wire  in_reset,  //  in_reset.reset, Reset Input
		output wire  out_reset  // out_reset.reset, Reset Output
	);

	assign out_reset = in_reset;

endmodule
