-- sys_reset_in.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sys_reset_in is
	port (
		in_reset  : in  std_logic := '0'; --  in_reset.reset, Reset Input
		out_reset : out std_logic         -- out_reset.reset, Reset Output
	);
end entity sys_reset_in;

architecture rtl of sys_reset_in is
begin

	out_reset <= in_reset;

end architecture rtl; -- of sys_reset_in
